apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-flask-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: calculator-flask
  template:
    metadata:
      labels:
        app: calculator-flask
    spec:
      containers:
        - name: calculator-flask
          image: yash5090/calculator-flask:latest # Replace with the actual image tag
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
