apiVersion: v1
kind: Service
metadata:
  name: calculator-flask-service
spec:
  selector:
    app: calculator-flask
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
